apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: freeflow-client
  name: freeflow-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: freeflow-client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: freeflow-client
    spec:
      containers:
        - command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          env:
            - name: LD_PRELOAD
              value: /freeflow/libfsocket.so
            - name: VNET_PREFIX
              value: 10.32.0.0/12 # default master node weave network
          image: jwmeister/freeflowclient:v1
          name: freeflow-client
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /freeflow
              name: freeflow-router-claim0
      restartPolicy: Always
      volumes:
        - name: freeflow-router-claim0
          persistentVolumeClaim:
            claimName: freeflow-router-claim0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - master-node-prod2
status: {}
