apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: freeflow-router
  name: freeflow-router
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: freeflow-router
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: freeflow-router
    spec:
      containers:
        - command: ["/bin/sh", "-ec", "./start.sh"]
          env:
            - name: HOST_IP_PREFIX
              value: 192.168.100.15/24
            - name: HOST_IP
              value: 192.168.100.15
          image: freeflow/freeflow:tcp
          name: freeflow-router
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /freeflow
              name: freeflow-router-claim0
      restartPolicy: Always
      volumes:
        - name: freeflow-router-claim0
          persistentVolumeClaim:
            claimName: freeflow-router-claim0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - master-node-prod2
status: {}
